name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions!"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: install deps from package.lock file
        run: npm install --frozen-lockfile
      - run: npm nx build restaurant
